mqtt:
  enabled: true
  host: core-mosquitto        # Mosquitto add-on hostname inside HA
  port: 1883
  user: admin               # RECOMMENDED: non-admin HA user (see step 2)
  password: admin         # set real password in step 2
  topic_prefix: frigate
  client_id: frigate


go2rtc: {}
live: {}

cameras:
  eversecu1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:tntrepair@192.168.1.171:10554/tcp/av0_0
          roles: [detect]
          input_args: -rtsp_transport tcp
          # If this fails, swap to ONE of these (then Save & Restart):
          # - path: rtsp://admin:tntrepair@192.168.1.171:554/Streaming/Channels/101
          #   roles: [detect]
          #   input_args: -rtsp_transport tcp
          # - path: rtsp://admin:tntrepair@192.168.1.171:554/h264Preview_01_main
          #   roles: [detect]
          #   input_args: -rtsp_transport tcp
    detect:
      enabled: true
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
