name: Validate Home Assistant
on: [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install yamllint jinja2
      - name: YAML Lint
        run: yamllint .
      - name: Validate HA configuration
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/home-assistant/home-assistant:stable
          options: -v ${{ github.workspace }}:/config
          run: bash -lc "hass --script check_config -c /config"